//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations.Schema;

namespace DAL.EF.WeatherForecast
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    [Table("DayWeather")]
    public partial class DayWeather
    {
        [Key]
        public int Id { get; set; }
        public System.DateTime Day { get; set; }
        public double DayTemperature { get; set; }
        public double NightTemperature { get; set; }
        public int IdImagePath { get; set; }
    
        public virtual ImagePath ImagePath { get; set; }
    }
}
